const events = [
  {
    id: 'tech-innovation-summit',
    title: 'Tech Innovation Summit',
    description: 'Explore the latest in tech with industry leaders and innovators.',
    fullDescription: 'The Tech Innovation Summit brings together the brightest minds in technology to discuss breakthroughs in AI, cloud computing, and digital transformation. Featuring keynote speakers, hands-on workshops, and networking sessions, this event is designed to inspire and equip professionals and students alike.',
    category: 'College',
    type: 'walkin',
    status: 'upcoming',
    date: 'April 15, 2026',
    time: '9:00 AM – 5:00 PM',
    location: 'Main Auditorium, Bldg. A',
    attendees: 210,
    capacity: 300,
    icon: '💡',
    gradient: 'grad-violet'
  },
  {
    id: 'web-dev-workshop',
    title: 'Web Development Workshop',
    description: 'Hands-on workshop covering modern web technologies and best practices.',
    fullDescription: 'Dive deep into the world of web development with this intensive hands-on workshop. Learn from experienced developers as they walk you through building full-stack applications using modern frameworks. Perfect for beginners and intermediate developers looking to level up their skills.',
    category: 'College',
    type: 'online',
    status: 'live',
    date: 'March 28, 2026',
    time: '1:00 PM – 4:00 PM',
    location: 'Zoom Webinar',
    attendees: 180,
    capacity: 200,
    icon: '🌐',
    gradient: 'grad-cyan'
  },
  {
    id: 'ai-ml-bootcamp',
    title: 'AI & ML Bootcamp',
    description: 'An intensive bootcamp on machine learning and AI fundamentals.',
    fullDescription: 'This three-day bootcamp covers machine learning algorithms, neural networks, and practical AI applications. Participants will work on real datasets and build their own models under the guidance of expert instructors. No prior AI experience required.',
    category: 'College',
    type: 'walkin',
    status: 'upcoming',
    date: 'April 22, 2026',
    time: '8:00 AM – 6:00 PM',
    location: 'Computer Lab 3, Bldg. C',
    attendees: 95,
    capacity: 120,
    icon: '🤖',
    gradient: 'grad-emerald'
  },
  {
    id: 'career-fair-2026',
    title: 'Career Fair 2026',
    description: 'Connect with top companies and explore exciting career opportunities.',
    fullDescription: 'The annual Career Fair 2026 is back and bigger than ever! Over 50 companies will be present to offer internships, part-time, and full-time positions. Bring your resume, dress to impress, and be ready to make lasting impressions on your future employers.',
    category: 'College',
    type: 'walkin',
    status: 'upcoming',
    date: 'May 5, 2026',
    time: '10:00 AM – 3:00 PM',
    location: 'Gymnasium, Bldg. B',
    attendees: 450,
    capacity: 500,
    icon: '🏢',
    gradient: 'grad-amber'
  },
  {
    id: 'design-thinking-workshop',
    title: 'Design Thinking Workshop',
    description: 'Learn the principles of design thinking to solve complex problems creatively.',
    fullDescription: 'This immersive workshop introduces participants to the five stages of design thinking: Empathize, Define, Ideate, Prototype, and Test. Work in teams to tackle real-world challenges and create innovative solutions using a human-centered approach.',
    category: 'SHS',
    type: 'walkin',
    status: 'past',
    date: 'March 10, 2026',
    time: '2:00 PM – 5:00 PM',
    location: 'Room 201, Bldg. D',
    attendees: 60,
    capacity: 60,
    icon: '🎨',
    gradient: 'grad-rose'
  },
  {
    id: 'internship-orientation',
    title: 'Internship Orientation 2026',
    description: 'Everything you need to know before starting your internship journey.',
    fullDescription: 'Get ready for your internship with this comprehensive orientation. Learn about workplace etiquette, professional communication, and how to make the most of your internship experience. Industry mentors will share tips and answer your questions.',
    category: 'Internship',
    type: 'online',
    status: 'upcoming',
    date: 'April 8, 2026',
    time: '3:00 PM – 5:00 PM',
    location: 'Google Meet',
    attendees: 130,
    capacity: 250,
    icon: '🎓',
    gradient: 'grad-purple'
  },
  {
    id: 'science-fair-shs',
    title: 'SHS Science Fair 2026',
    description: 'Showcase your research and compete for top honors in science.',
    fullDescription: 'The annual SHS Science Fair is an opportunity for senior high school students to present their research projects and experiments to a panel of judges from academia and industry. Winners will receive scholarships and recognition at the graduation ceremony.',
    category: 'SHS',
    type: 'walkin',
    status: 'upcoming',
    date: 'April 30, 2026',
    time: '8:00 AM – 12:00 PM',
    location: 'Science Building, Bldg. E',
    attendees: 200,
    capacity: 350,
    icon: '🔬',
    gradient: 'grad-teal'
  },
  {
    id: 'internship-networking',
    title: 'Intern Networking Night',
    description: 'Build connections with fellow interns and industry professionals.',
    fullDescription: 'A relaxed evening event designed to help interns from various companies connect with each other and with experienced professionals. Share experiences, exchange contacts, and build the network that will support your career for years to come.',
    category: 'Internship',
    type: 'walkin',
    status: 'live',
    date: 'March 25, 2026',
    time: '6:00 PM – 9:00 PM',
    location: 'Events Hall, Ground Floor',
    attendees: 88,
    capacity: 100,
    icon: '🤝',
    gradient: 'grad-indigo'
  }
];
